import { ToyCategory } from '../../../src/entities/ToyCategory';

export const FriendSeed = [
  {
    id: 0,
    title: 'test',
    price: 10000,
    priceCd: '',
    month: 12,
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    kind: 'kind test',
    toyCollection: {
      id: 0,
      collection: 'toddle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 1,
    title: 'test2',
    price: 15000,
    priceCd: '',
    month: 12,
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    kind: 'kind test',
    toyCollection: {
      id: 0,
      collection: 'toddle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2,
    title: 'test3',
    price: 10000,
    priceCd: '',
    month: 12,
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    kind: 'kind test',
    toyCollection: {
      id: 0,
      collection: 'toddle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 3,
    title: 'test4',
    price: 10000,
    priceCd: '',
    month: 12,
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    kind: 'kind test',
    toyCollection: {
      id: 0,
      collection: 'toddle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
];
