import { ToyCategory } from '../../../src/entities/ToyCategory';

export const FriendSeed = [
  {
    id: 0,
    title: 'test',
    price: '10,000원',
    month: 12,
    link: 'test.com',
    playHow: 'test',
    kind: 'kind test',
    collection: 'collection test',
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 1,
    title: 'test2',
    price: '10,000원',
    month: 12,
    link: 'test.com',
    playHow: 'test',
    kind: 'kind test',
    collection: 'collection test',
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2,
    title: 'test3',
    price: '10,000원',
    month: 12,
    link: 'test.com',
    playHow: 'test',
    kind: 'kind test',
    collection: 'collection test',
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 3,
    title: 'test4',
    price: '10,000원',
    month: 12,
    link: 'test.com',
    playHow: 'test',
    kind: 'kind test',
    collection: 'collection test',
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
];
