import { ToyCategory } from '../../../src/entities/ToyCategory';

export const ToySeed = [
  {
    id: 3017,
    title: 'test',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 1,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2733,
    title: 'test2',
    price: 15000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 2,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2878,
    title: 'test2',
    price: 15000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 2,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2767,
    title: 'test3',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 5,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2989,
    title: 'test3',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 5,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2943,
    title: 'test3',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 5,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2889,
    title: 'test4',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 3,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2826,
    title: 'test4',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 3,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2789,
    title: 'test4',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 3,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: 2804,
    title: 'test4',
    price: 10000,
    priceCd: 0,
    month: '12',
    minMonth: 1,
    maxMonth: 10,
    link: 'test.com',
    playHow: 'test',
    playHowCd: 0,
    toySiteCd: 3,
    toyCollection: {
      id: 0,
      title: 'title',
      image: 'image',
      subtitle: 'subtitle',
      createdAt: `${new Date()}`,
      updatedAt: `${new Date()}`,
    },
    category: 'category',
    categoryCd: 2,
    image: 'image.com',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
];
